In [2]:
import numpy as np
X=np.array([[1,2,3],[4,5,6],[7,8,9]])
#perform svd
U,S,VT=np.linalg.svd(X)
#choose the no of compont
n_components=2
#reconstruct the  matrix with reduced dimension
X_reconstructed=np.dot(U[:,:n_components],np.dot(np.diag(S[:n_components]),VT[:n_components,:]))
print("Orginal matrix:")
print(X)
print("\nReconstructed Matrixwith reduced dimension::")
print(X_reconstructed)

Orginal matrix:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Reconstructed Matrixwith reduced dimension::
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
